// Integration test: transcribes fixtures/utterance.pcm with the REAL whisper-cli.exe + real
// ggml-small.en.bin model (no fakes). Skipped entirely when the provisioned models aren't on
// disk (see cdd/tasks/stt-whisper.md) so CI/checkouts without `npm run fetch-models` still pass.
//
// fixtures/utterance.pcm is 16kHz mono s16 raw PCM (no WAV header) generated by piping the text
// "What time is it?" through the provisioned Piper voice (models/piper/en_US-lessac-medium.onnx,
// which outputs 22050Hz mono WAV) and resampling to 16kHz with the provisioned ffmpeg.exe — see
// the task's "Fixture note" for the exact generation steps. It is small enough (~33KB) to commit.

import { describe, expect, it } from 'vitest';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { WhisperCppStt } from '../src/voice/stt';
import { resolveModelPaths } from '../src/main/modelPaths';

const here = dirname(fileURLToPath(import.meta.url));
// test/ -> app/ -> packages/ -> repo root
const repoRoot = join(here, '..', '..', '..');
const modelsRoot = join(repoRoot, 'models');

const paths = resolveModelPaths({ modelsRoot });
const modelsPresent = !('missing' in paths);

function loadFixturePcm(): Int16Array {
  const buf = readFileSync(join(here, 'fixtures', 'utterance.pcm'));
  const samples = new Int16Array(buf.length / 2);
  for (let i = 0; i < samples.length; i++) {
    samples[i] = buf.readInt16LE(i * 2);
  }
  return samples;
}

describe.skipIf(!modelsPresent)('WhisperCppStt (real whisper-cli + ggml-small.en.bin)', () => {
  it('transcribes fixtures/utterance.pcm ("what time is it") containing "time"', async () => {
    if ('missing' in paths) throw new Error('unreachable — guarded by describe.skipIf');

    const stt = new WhisperCppStt({ whisperCliPath: paths.whisperCli });
    await stt.init({ modelPath: paths.whisperModel });

    const audio = loadFixturePcm();
    const result = await stt.transcribe(audio);

    // eslint-disable-next-line no-console
    console.log(`[stt.integration] transcript=${JSON.stringify(result.text)} ms=${result.ms}`);

    expect(result.text.toLowerCase()).toContain('time');
    expect(result.ms).toBeGreaterThan(0);
  }, 30_000);
});
